name: ci

on:
  workflow_dispatch:
  # push:
  #  branches:
  #    - master
  # schedule:
  #  - cron: '0 4 * * *' # 每天上午10执行

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  execute:
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # 作用：检出仓库，获取源码。
      - name: Install Node 14
        uses: actions/setup-node@v3 # uses 和 run 不能同时在一个step使用
        with:
          node-version: 14
      - name: Install packages
        run: npm install
      - name: run
        env:
          MT_COOKIE: ${{ secrets.MT_COOKIE }}
          MT_DEVICEID: ${{ secrets.MT_DEVICEID }}
          BARK: ${{ secrets.BARK }}
        run: |
          chmod 777 indexAction.js
          node ./indexAction.js
